PRAGMA foreign_keys = ON;

-- v41 draft-board refresh. Run this before the 2026 draft begins.
-- This intentionally replaces the v40 preseason draft board with the commissioner-updated board.
DELETE FROM draft_slots WHERE season=2026;
DELETE FROM draft_pool WHERE season=2026;
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,1.0,1,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,2.0,2,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,3.0,3,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,4.0,4,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,5.0,5,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,6.0,6,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,7.0,7,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,8.0,8,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,9.0,9,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,10.0,10,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,11.0,11,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,12.0,12,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,13.0,13,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,14.0,14,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,15.0,15,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,16.0,16,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,17.0,17,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,18.0,18,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,19.0,19,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,20.0,20,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,21.0,21,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,22.0,22,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,23.0,23,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,24.0,24,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,25.0,25,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,26.0,26,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,27.0,27,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,28.0,28,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,29.0,29,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,30.0,30,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,31.0,31,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,32.0,32,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,33.0,33,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,34.0,34,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,35.0,35,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,36.0,36,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,37.0,37,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,38.0,38,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,39.0,39,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,40.0,40,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,41.0,41,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,42.0,42,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,43.0,43,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,44.0,44,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,45.0,45,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,46.0,46,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,47.0,47,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,48.0,48,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,49.0,49,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,50.0,50,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,51.0,51,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,52.0,52,'silverbacks','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,53.0,53,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,54.0,54,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,55.0,55,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,56.0,56,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,57.0,57,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,58.0,58,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,59.0,59,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,60.0,60,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,61.0,61,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,62.0,62,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,63.0,63,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,64.0,64,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,65.0,65,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,66.0,66,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,67.0,67,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,68.0,68,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,69.0,69,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,70.0,70,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,71.0,71,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,72.0,72,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,73.0,73,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,74.0,74,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,75.0,75,'silverbacks','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,76.0,76,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,20.5,NULL,'silverbacks','reserved','Ryan Soenen','Ryan Soenen',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,22.5,NULL,'stiff-wifflers','reserved','Will Carter V','Will Carter V',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,25.5,NULL,'silverbacks','reserved','Ben Hicks','Ben Hicks',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,26.5,NULL,'silverbacks','reserved','Jason Marrs','Jason Marrs',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,34.5,NULL,'silverbacks','reserved','Jose Aranda','Jose Aranda',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,50.5,NULL,'silverbacks','reserved','Camden Kirchgessner','Camden Kirchgessner',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,58.5,NULL,'silverbacks','reserved','Jack Romkema','Jack Romkema',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,66.5,NULL,'silverbacks','reserved','Kirby Bach','Kirby Bach',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Gerard Sharkey',NULL,1,7,9,8,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Landon Edwards',NULL,2,8,9,8,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Eddie McGettigan',NULL,3,6,9,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ian Phelps',NULL,4,5,5,8,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Alex Rivera',NULL,5,6,9,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Logan Bettinger',NULL,6,6,9,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Kevin Curna',NULL,7,6,7,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Xavier Hirsch',NULL,8,2,10,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Diego Alonso',NULL,9,8,6,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Andrew Frey',NULL,10,7,7,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Joseph Dachnowicz',NULL,11,4,7,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Freddy Zeckser',NULL,12,6,7,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Collin Barker',NULL,13,5,7,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Tim Baldwin',NULL,14,4,6,5,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Stephen Sclafani',NULL,15,5,6,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Bobby Wolff',NULL,16,5,6,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jimmy Szpak',NULL,17,8,6,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ryan Hyer',NULL,18,8,6,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Will Cohn',NULL,19,7,5,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Bennett Alvarado',NULL,20,6,6,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Nick Hulgrave',NULL,21,6,4,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'JP Cardenas',NULL,22,6,6,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Quinn Brown',NULL,23,4,6,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Christopher Marvel',NULL,24,5,6,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Connor Savage',NULL,25,4,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Nik Husarik',NULL,26,6,5,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ryan McCain',NULL,27,6,6,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Nick Swiderski',NULL,28,3,6,2,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ryan Allen',NULL,29,5,5,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jaden Lukose',NULL,30,6,6,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Aiden O''Reilly',NULL,31,5,5,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Anthony Lucatuorto',NULL,32,5,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jack Dunn',NULL,33,5,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Matt Schuenemann',NULL,34,4,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ben Meyer',NULL,35,3,4,8,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Maximilian Busk',NULL,36,4,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Brady Cahill',NULL,37,5,5,5,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Adam Skrzypczyk',NULL,38,6,4,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jeb Blanco',NULL,39,4,4,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Joe O''Melveny',NULL,40,5,4,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Donny Edwards',NULL,41,4,3,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Chase Niemeyer',NULL,42,4,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'John Savage',NULL,43,3,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Patrick Gareau',NULL,44,4,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Danny Kennedy',NULL,45,4,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Zach Zywiec',NULL,46,4,3,2,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Alex Tsvetkov',NULL,47,5,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Chuck Menard',NULL,48,5,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Charlie Doherty',NULL,49,2,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jack Powers',NULL,50,5,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Liam Lyon',NULL,51,4,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Teddy Skendzel',NULL,52,5,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Anthony Bellone',NULL,53,3,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Robby Diamond',NULL,54,4,2,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Freddy Rudolph',NULL,55,2,2,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Sebastian Borjas',NULL,56,3,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ryan Walsh',NULL,57,3,2,2,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'James Baird',NULL,58,3,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Michael Budd',NULL,59,3,2,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Charlie Chevalier',NULL,60,1,2,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Nathan Skendzel',NULL,61,4,1,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Justin Murray',NULL,62,4,1,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Rob Marshall',NULL,63,2,1,1,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Sam Spolyar',NULL,64,NULL,NULL,NULL,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ben Jollay',NULL,65,NULL,NULL,NULL,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Patrick Collins',NULL,66,NULL,NULL,NULL,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Rainier Gilliss',NULL,67,NULL,NULL,NULL,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Johnny Carey',NULL,68,NULL,NULL,NULL,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Silas Carder',NULL,69,NULL,NULL,NULL,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Noah Adkins',NULL,70,NULL,NULL,NULL,'available');
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Ryan Soenen' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Will Carter V' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Ben Hicks' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Jason Marrs' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Jose Aranda' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Camden Kirchgessner' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Jack Romkema' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Kirby Bach' COLLATE NOCASE;
