PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS team_rosters (
  season INTEGER NOT NULL,
  player_id TEXT NOT NULL REFERENCES players(player_id) ON DELETE CASCADE,
  team_id TEXT NOT NULL REFERENCES teams(team_id),
  role TEXT NOT NULL DEFAULT 'player' CHECK (role IN ('player','captain','protected')),
  assigned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  assigned_by TEXT NOT NULL,
  PRIMARY KEY (season, player_id)
);
CREATE INDEX IF NOT EXISTS idx_team_rosters_season_team ON team_rosters(season, team_id);

DELETE FROM draft_slots WHERE season=2026;
DELETE FROM draft_pool WHERE season=2026;
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,1.0,1,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,2.0,2,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,3.0,3,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,4.0,4,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,5.0,5,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,6.0,6,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,7.0,7,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,8.0,8,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,9.0,9,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,10.0,10,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,11.0,11,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,12.0,12,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,13.0,13,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,14.0,14,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,15.0,15,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,16.0,16,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,17.0,17,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,18.0,18,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,19.0,19,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,20.0,20,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,21.0,21,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,22.0,22,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,23.0,23,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,24.0,24,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,25.0,25,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,26.0,26,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,27.0,27,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,28.0,28,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,29.0,29,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,30.0,30,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,31.0,31,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,32.0,32,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,33.0,33,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,34.0,34,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,35.0,35,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,36.0,36,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,37.0,37,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,38.0,38,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,39.0,39,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,40.0,40,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,41.0,41,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,42.0,42,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,43.0,43,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,44.0,44,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,45.0,45,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,46.0,46,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,47.0,47,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,48.0,48,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,49.0,49,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,50.0,50,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,51.0,51,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,52.0,52,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,53.0,53,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,54.0,54,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,55.0,55,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,56.0,56,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,57.0,57,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,58.0,58,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,59.0,59,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,60.0,60,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,61.0,61,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,62.0,62,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,63.0,63,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,64.0,64,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,65.0,65,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,66.0,66,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,67.0,67,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,68.0,68,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,69.0,69,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,selected_player_name,selected_at,notes) VALUES(2026,70.0,70,'silverbacks','pick','Kirby Bach',CURRENT_TIMESTAMP,'Pre-filled numbered selection supplied by commissioner.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,71.0,71,'storm','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,72.0,72,'stiff-wifflers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,73.0,73,'midnight','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,74.0,74,'goofy-goobers','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,75.0,75,'dirty-dawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,76.0,76,'ball-busters','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,77.0,77,'twin-titans','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,78.0,78,'silverbacks','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type) VALUES(2026,79.0,79,'underdawgs','pick');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,27.5,NULL,'silverbacks','reserved','Ryan Soenen','Ryan Soenen',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,28.5,NULL,'silverbacks','reserved','Ben Hicks','Ben Hicks',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,36.1,NULL,'silverbacks','reserved','Jason Marrs','Jason Marrs',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,36.2,NULL,'underdawgs','reserved','Stephen Sclafani','Stephen Sclafani',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,43.5,NULL,'silverbacks','reserved','Camden Kirchgessner','Camden Kirchgessner',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,51.1,NULL,'silverbacks','reserved','Jason Aranda','Jason Aranda',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,51.2,NULL,'underdawgs','reserved','Robby Diamond','Robby Diamond',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,51.3,NULL,'silverbacks','reserved','Oscar Uy','Oscar Uy',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,51.4,NULL,'stiff-wifflers','reserved','Will Carter V','Will Carter V',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,55.1,NULL,'twin-titans','reserved','Michael Camilleri','Michael Camilleri',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,55.2,NULL,'silverbacks','reserved','Adam Skrzypczyck','Adam Skrzypczyck',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,55.3,NULL,'underdawgs','reserved','Ryan Walsh','Ryan Walsh',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,62.5,NULL,'underdawgs','reserved','Rob Marshall','Rob Marshall',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_slots(season,sequence,pick_number,team_id,slot_type,reserved_player_name,selected_player_name,selected_at,notes) VALUES(2026,70.5,NULL,'underdawgs','reserved','Dan Smith','Dan Smith',CURRENT_TIMESTAMP,'Reserved roster selection; comparable draft value forfeited.');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Gerard Sharkey',NULL,1,7,9,8,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Landon Edwards',NULL,2,8,9,8,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Eddie McGettigan',NULL,3,6,9,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Alex Rivera',NULL,4,6,9,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Logan Bettinger',NULL,5,6,9,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Kevin Curran',NULL,6,6,7,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Sam Spolyar',NULL,7,6,9,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ian Phelps',NULL,8,5,5,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Andrew Frey',NULL,9,7,7,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Joseph Dachnowicz',NULL,10,4,7,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Freddy Zeckser',NULL,11,6,7,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Diego Alonso',NULL,12,8,6,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Collin Barker',NULL,13,5,7,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Tommy Wollscheid',NULL,14,5,7,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Xavier Hirsch',NULL,15,2,10,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Tim Baldwin',NULL,16,4,6,5,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Bobby Wolff',NULL,17,5,6,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jacob Bailey',NULL,18,7,6,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jimmy Szpak',NULL,19,8,6,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Will Cohn',NULL,20,7,7,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ryan Hyer',NULL,21,8,6,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Liam Kaseburg',NULL,22,3,8,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jimmy Suter',NULL,23,7,7,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Dean Zervos',NULL,24,4,6,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Bennett Alvarado',NULL,25,6,6,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Nick Hulgrave',NULL,26,6,4,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'JP Cardenas',NULL,27,6,6,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Quinn Brown',NULL,28,4,6,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Christopher Marvel',NULL,29,5,6,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Connor Savage',NULL,30,4,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Nik Husarik',NULL,31,6,5,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ryan McCain',NULL,32,6,6,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ben Meyer',NULL,33,3,4,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Nick Swiderski',NULL,34,3,6,2,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ryan Allen',NULL,35,5,5,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jaden Lukose',NULL,36,6,6,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Aiden O''Reilly',NULL,37,5,5,3,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Anthony Lucatuorto',NULL,38,5,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jack Dunn',NULL,39,5,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Matt Schuenemann',NULL,40,4,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Maximilian Busk',NULL,41,4,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Liam Hill',NULL,42,4,3,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Brady Cahill',NULL,43,5,5,5,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jeb Blanco',NULL,44,4,4,7,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Joe O''Melveny',NULL,45,5,4,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Donny Edwards',NULL,46,4,3,6,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Chase Niemeyer',NULL,47,4,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'John Savage',NULL,48,3,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Patrick Gareau',NULL,49,4,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Danny Kennedy',NULL,50,4,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Zach Zywiec',NULL,51,4,3,2,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Alex Tsvetkov',NULL,52,5,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Andrew Le',NULL,53,5,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Chuck Menard',NULL,54,5,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Charlie Doherty',NULL,55,2,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jack Powers',NULL,56,5,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jack Conners',NULL,57,6,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Patrick Collins',NULL,58,2,5,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Liam Lyon',NULL,59,4,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Teddy Skendzel',NULL,60,5,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Rainier Gilliss',NULL,61,5,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Noah Adkins',NULL,62,2,4,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Anthony Bellone',NULL,63,3,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Freddy Rudolph',NULL,64,2,2,4,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Noah Cerniglia',NULL,65,3,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Sebastian Borjas',NULL,66,3,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Kevin Harnish',NULL,67,5,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'James Baird',NULL,68,3,3,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Michael Budd',NULL,69,3,2,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Charlie Chevalier',NULL,70,1,2,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Nathan Skendzel',NULL,71,4,1,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Patrick Jackson',NULL,72,4,2,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Justin Murray',NULL,73,4,1,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Jacob Bechtel',NULL,74,2,1,0,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Ben Jollay',NULL,75,NULL,NULL,NULL,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Johnny Carey',NULL,76,NULL,NULL,NULL,'available');
INSERT OR IGNORE INTO draft_pool(season,player_id,name,class_year,projected_pick,projected_series_played,projected_batter_rank,projected_pitcher_rank,status) VALUES(2026,NULL,'Silas Carder',NULL,77,NULL,NULL,NULL,'available');
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Ryan Soenen' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Ben Hicks' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Jason Marrs' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Stephen Sclafani' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Camden Kirchgessner' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Jason Aranda' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Robby Diamond' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Oscar Uy' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Will Carter V' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Michael Camilleri' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Adam Skrzypczyck' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Ryan Walsh' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Rob Marshall' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Dan Smith' COLLATE NOCASE;
UPDATE draft_pool SET status='reserved' WHERE season=2026 AND name='Kirby Bach' COLLATE NOCASE;
