SELECT 1;

CREATE TABLE IF NOT EXISTS fantasy_player_baselines (
  player_id TEXT PRIMARY KEY REFERENCES players(player_id) ON DELETE CASCADE,
  batting_fp_per_game REAL,
  career_pa INTEGER NOT NULL DEFAULT 0,
  career_batting_gp INTEGER NOT NULL DEFAULT 0,
  pitching_fp_per_app REAL,
  career_pitching_apps INTEGER NOT NULL DEFAULT 0,
  career_pitching_outs INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS fantasy_slates (
  slate_date TEXT PRIMARY KEY,
  season INTEGER NOT NULL DEFAULT 2026,
  lock_time TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','locked','final')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by TEXT NOT NULL DEFAULT 'system'
);

CREATE TABLE IF NOT EXISTS fantasy_player_settings (
  slate_date TEXT NOT NULL REFERENCES fantasy_slates(slate_date) ON DELETE CASCADE,
  player_id TEXT NOT NULL REFERENCES players(player_id) ON DELETE CASCADE,
  batting_eligible INTEGER NOT NULL DEFAULT 1 CHECK (batting_eligible IN (0,1)),
  pitching_eligible INTEGER NOT NULL DEFAULT 1 CHECK (pitching_eligible IN (0,1)),
  batting_multiplier_override REAL,
  pitching_multiplier_override REAL,
  PRIMARY KEY (slate_date,player_id)
);

CREATE TABLE IF NOT EXISTS fantasy_entries (
  entry_id INTEGER PRIMARY KEY AUTOINCREMENT,
  slate_date TEXT NOT NULL REFERENCES fantasy_slates(slate_date) ON DELETE CASCADE,
  display_name TEXT NOT NULL,
  display_key TEXT NOT NULL,
  submitted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (slate_date,display_key)
);

CREATE TABLE IF NOT EXISTS fantasy_picks (
  entry_id INTEGER NOT NULL REFERENCES fantasy_entries(entry_id) ON DELETE CASCADE,
  slot_type TEXT NOT NULL CHECK (slot_type IN ('bat','pit')),
  slot_number INTEGER NOT NULL,
  player_id TEXT NOT NULL REFERENCES players(player_id),
  multiplier REAL NOT NULL CHECK (multiplier >= 1 AND multiplier <= 6),
  PRIMARY KEY (entry_id,slot_type,slot_number)
);

CREATE INDEX IF NOT EXISTS idx_fantasy_entries_date ON fantasy_entries(slate_date);
CREATE INDEX IF NOT EXISTS idx_fantasy_picks_player ON fantasy_picks(player_id);

INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.00000000,2,1,-14.00000000,1,1 FROM players WHERE player_id='aiden_o_reilly';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.50000000,25,10,NULL,0,0 FROM players WHERE player_id='alex_tsvetkov';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,3.14000000,203,50,5.78947368,19,122 FROM players WHERE player_id='andrew_borgie';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.11111111,24,9,NULL,0,0 FROM players WHERE player_id='andrew_letherman';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.54545455,126,33,NULL,0,0 FROM players WHERE player_id='andrew_shin';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,5.00000000,11,4,2.00000000,1,3 FROM players WHERE player_id='andy_o_neil';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.31818182,67,22,-5.00000000,1,4 FROM players WHERE player_id='anthony_bellone';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.66666667,52,15,-4.00000000,1,1 FROM players WHERE player_id='anthony_lucatuorto';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.33333333,10,3,-1.00000000,1,1 FROM players WHERE player_id='armand_martinez';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.33333333,60,18,-4.00000000,5,9 FROM players WHERE player_id='aryan_patel';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.46153846,54,13,NULL,0,0 FROM players WHERE player_id='austin_mcmahon';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-2.00000000,5,2,NULL,0,0 FROM players WHERE player_id='ben_eppich';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.66666667,17,3,33.00000000,1,27 FROM players WHERE player_id='ben_meyer';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.09523810,57,21,-10.00000000,1,2 FROM players WHERE player_id='bennett_ruskusky';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,3.45000000,78,20,NULL,0,0 FROM players WHERE player_id='bobby_wolff';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.66666667,57,15,-3.22222222,9,44 FROM players WHERE player_id='brady_soenen';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.25000000,22,8,11.00000000,5,49 FROM players WHERE player_id='brendan_mato';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.81250000,170,48,-1.50000000,18,94 FROM players WHERE player_id='brendan_pruitt';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,4.65000000,84,20,-1.66666667,12,80 FROM players WHERE player_id='brendon_allen';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.14285714,14,7,NULL,0,0 FROM players WHERE player_id='buzz_djikaitty';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,22,9,NULL,0,0 FROM players WHERE player_id='caden_baudek';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,80,23,NULL,0,0 FROM players WHERE player_id='carter_verst';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.06666667,518,105,4.54022989,87,552 FROM players WHERE player_id='casey_cavlovich';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.19718310,222,71,-2.00000000,6,19 FROM players WHERE player_id='charlie_brady';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.05000000,92,20,NULL,0,0 FROM players WHERE player_id='charlie_chevalier';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-1.00000000,6,2,NULL,0,0 FROM players WHERE player_id='charlie_true';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.28000000,62,25,NULL,0,0 FROM players WHERE player_id='chase_niemeyer';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-1.00000000,2,2,NULL,0,0 FROM players WHERE player_id='christian_kuehl';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.42857143,136,28,7.00000000,16,140 FROM players WHERE player_id='colin_dwyer';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-1.30000000,26,10,0.00000000,1,1 FROM players WHERE player_id='colin_moore';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-1.00000000,8,4,NULL,0,0 FROM players WHERE player_id='connor_burke';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.82352941,192,51,-1.22580645,31,165 FROM players WHERE player_id='connor_dove';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.20000000,16,5,NULL,0,0 FROM players WHERE player_id='connor_malone';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.20000000,15,5,NULL,0,0 FROM players WHERE player_id='connor_savage';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.75000000,15,4,NULL,0,0 FROM players WHERE player_id='connor_wible';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.66666667,12,3,NULL,0,0 FROM players WHERE player_id='cooper_werner';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-3.00000000,4,1,NULL,0,0 FROM players WHERE player_id='daman_bhalla';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.20000000,14,5,NULL,0,0 FROM players WHERE player_id='dan_corcoran';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.23404255,194,47,-1.02777778,36,229 FROM players WHERE player_id='danny_donegan';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.31250000,68,32,NULL,0,0 FROM players WHERE player_id='danny_kennedy';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-1.00000000,3,2,NULL,0,0 FROM players WHERE player_id='david_buckley';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-2.00000000,6,3,NULL,0,0 FROM players WHERE player_id='david_de_la_cruz';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,NULL,0,0,-2.00000000,1,1 FROM players WHERE player_id='dennis_gunn';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.26470588,114,34,-0.50000000,8,38 FROM players WHERE player_id='diego_alonso';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.66666667,7,3,-4.00000000,1,2 FROM players WHERE player_id='dom_dehaven';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.50000000,6,4,NULL,0,0 FROM players WHERE player_id='domingo_huerta';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.33333333,6,3,15.00000000,1,9 FROM players WHERE player_id='dylan_passo';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.90000000,186,60,4.52380952,42,276 FROM players WHERE player_id='eddie_devine';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.97590361,287,83,-0.80000000,10,52 FROM players WHERE player_id='eddie_donovan';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-2.00000000,2,1,NULL,0,0 FROM players WHERE player_id='edmond_meng';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.83783784,144,37,1.00000000,24,136 FROM players WHERE player_id='ethan_moye';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.80000000,180,50,-0.17391304,23,150 FROM players WHERE player_id='evan_reid';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.89130435,189,46,0.00000000,22,91 FROM players WHERE player_id='gavin_ross';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.58620690,84,29,2.62500000,8,53 FROM players WHERE player_id='gerard_sharkey';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.82608696,70,23,NULL,0,0 FROM players WHERE player_id='gordie_mcdonnell';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.86666667,49,15,0.66666667,6,39 FROM players WHERE player_id='grant_spielbauer';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.13888889,258,72,-7.62500000,24,112 FROM players WHERE player_id='guy_maiorano';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.23529412,59,17,NULL,0,0 FROM players WHERE player_id='holden_coyle';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,7,3,NULL,0,0 FROM players WHERE player_id='ian_lawler';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.16666667,11,6,NULL,0,0 FROM players WHERE player_id='ian_nordland';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,4.59375000,122,32,-0.30000000,20,127 FROM players WHERE player_id='isaac_oswald';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.33333333,21,6,NULL,0,0 FROM players WHERE player_id='jack_dunn';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,3.16666667,47,12,-9.00000000,1,1 FROM players WHERE player_id='jack_foster';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.60215054,375,93,-1.14705882,34,173 FROM players WHERE player_id='jack_glavy';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.19512195,131,41,-2.60000000,5,13 FROM players WHERE player_id='jack_morrow';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,4.38461538,188,39,1.71428571,7,33 FROM players WHERE player_id='jack_penney';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.13333333,39,15,NULL,0,0 FROM players WHERE player_id='jack_powers';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.08510638,188,47,0.19047619,42,279 FROM players WHERE player_id='jack_terry';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.38461538,223,65,-8.93333333,15,68 FROM players WHERE player_id='jacob_clark';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.71428571,36,14,-2.00000000,4,22 FROM players WHERE player_id='jacob_olejnik';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.00000000,25,13,-5.00000000,1,3 FROM players WHERE player_id='jaden_lukose';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.42253521,263,71,NULL,0,0 FROM players WHERE player_id='james_stevens';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.25974026,280,77,-7.00000000,12,32 FROM players WHERE player_id='james_walsh';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.03125000,93,32,1.59090909,22,137 FROM players WHERE player_id='jeb_blanco';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,3.23809524,77,21,-1.21428571,14,88 FROM players WHERE player_id='jerry_vielhauer';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,4.86666667,229,45,-1.37037037,27,186 FROM players WHERE player_id='jimmy_redfern';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.04166667,88,24,-2.62500000,8,27 FROM players WHERE player_id='jimmy_szpak';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.12500000,25,8,NULL,0,0 FROM players WHERE player_id='joe_bart';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.86956522,68,23,-5.16666667,6,28 FROM players WHERE player_id='joe_o_melveny';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-4.00000000,5,1,NULL,0,0 FROM players WHERE player_id='joe_zinkan';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.37500000,28,8,-2.33333333,6,30 FROM players WHERE player_id='joey_spence';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.40000000,194,60,3.97222222,36,256 FROM players WHERE player_id='joey_thomalla';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.66666667,11,6,NULL,0,0 FROM players WHERE player_id='john_abood';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.87500000,21,8,NULL,0,0 FROM players WHERE player_id='john_boscarino';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,13,3,NULL,0,0 FROM players WHERE player_id='john_casson';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.80000000,9,5,NULL,0,0 FROM players WHERE player_id='john_masjak';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.00000000,129,33,-2.20000000,5,15 FROM players WHERE player_id='johnny_toole';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-1.00000000,6,3,NULL,0,0 FROM players WHERE player_id='jorge_hernandez';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.88888889,29,9,NULL,0,0 FROM players WHERE player_id='josh_chen';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.25000000,39,12,-2.50000000,4,25 FROM players WHERE player_id='jp_cardenas';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.64705882,256,68,-7.66666667,6,28 FROM players WHERE player_id='jt_kaiser';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-1.61538462,43,13,NULL,0,0 FROM players WHERE player_id='justin_murray';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.42857143,21,7,NULL,0,0 FROM players WHERE player_id='justin_zych';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.80000000,54,15,-0.72727273,11,60 FROM players WHERE player_id='kade_hennessy';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.20000000,10,5,NULL,0,0 FROM players WHERE player_id='kieran_sims';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.12500000,21,8,NULL,0,0 FROM players WHERE player_id='kyler_mccormack';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.12500000,23,8,NULL,0,0 FROM players WHERE player_id='liam_emerick';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.46153846,36,13,-16.00000000,1,1 FROM players WHERE player_id='liam_kelly';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,5,1,NULL,0,0 FROM players WHERE player_id='liam_novak';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.09433962,169,53,0.70000000,10,53 FROM players WHERE player_id='luke_gormsen';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,4,3,NULL,0,0 FROM players WHERE player_id='luke_grantz';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.66666667,8,3,NULL,0,0 FROM players WHERE player_id='luke_parikh';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.20000000,44,15,-6.25000000,4,10 FROM players WHERE player_id='luke_woodyard';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.00000000,63,15,2.55555556,9,70 FROM players WHERE player_id='luke_wronski';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,14,3,NULL,0,0 FROM players WHERE player_id='maddie_taylor';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.39130435,186,46,0.50000000,2,12 FROM players WHERE player_id='mark_potts';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.66666667,10,3,-4.00000000,1,3 FROM players WHERE player_id='mason_barth';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.57142857,22,7,4.20000000,5,39 FROM players WHERE player_id='matt_baird';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.90789474,310,76,5.57692308,52,417 FROM players WHERE player_id='matt_baldwin';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.33333333,6,3,NULL,0,0 FROM players WHERE player_id='matt_flowers';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.11111111,22,9,2.00000000,2,9 FROM players WHERE player_id='matt_gough';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.40000000,13,5,NULL,0,0 FROM players WHERE player_id='matt_murawski';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.50000000,26,6,NULL,0,0 FROM players WHERE player_id='matt_potter';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.40000000,24,5,NULL,0,0 FROM players WHERE player_id='matt_schuenemann';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.33333333,9,3,NULL,0,0 FROM players WHERE player_id='matt_stewart';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.92792793,417,111,6.34831461,89,577 FROM players WHERE player_id='matthew_doty';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.00000000,38,9,2.33333333,3,21 FROM players WHERE player_id='matthew_pilger';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.17391304,81,23,NULL,0,0 FROM players WHERE player_id='max_dow';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.33333333,8,3,-5.00000000,2,3 FROM players WHERE player_id='max_partovi';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.50000000,19,8,NULL,0,0 FROM players WHERE player_id='michael_budd';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.00000000,22,10,NULL,0,0 FROM players WHERE player_id='michael_camilleri';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.20000000,12,5,NULL,0,0 FROM players WHERE player_id='michael_nobrega';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,3.32835821,537,134,2.97297297,111,649 FROM players WHERE player_id='michael_pilger';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.20000000,20,5,-0.66666667,3,17 FROM players WHERE player_id='mike_holt';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.26666667,39,15,-1.00000000,3,8 FROM players WHERE player_id='nate_ernst';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.11111111,24,9,NULL,0,0 FROM players WHERE player_id='nathan_skendzel';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.25000000,60,20,0.44444444,18,104 FROM players WHERE player_id='nick_hulgrave';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,3.00000000,59,14,NULL,0,0 FROM players WHERE player_id='nick_parten';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.85714286,21,7,2.00000000,1,6 FROM players WHERE player_id='nick_seifried';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.10000000,29,10,1.50000000,2,5 FROM players WHERE player_id='nik_husarik';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.19047619,53,21,NULL,0,0 FROM players WHERE player_id='noah_cerniglia';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.44444444,21,9,-7.50000000,4,6 FROM players WHERE player_id='noah_pellot';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.78571429,165,42,-5.37500000,8,20 FROM players WHERE player_id='owen_mccandless';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.33333333,8,3,NULL,0,0 FROM players WHERE player_id='pat_domler';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.12500000,27,8,NULL,0,0 FROM players WHERE player_id='patrick_buckel';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.35897436,309,78,-1.88888889,54,336 FROM players WHERE player_id='patrick_fitzgerald';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.66666667,16,6,NULL,0,0 FROM players WHERE player_id='patrick_jackson';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.60784314,201,51,-0.54838710,31,210 FROM players WHERE player_id='patrick_sullivan';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,3.35849057,493,106,-0.37313433,67,322 FROM players WHERE player_id='patrick_thompson';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.86666667,47,15,NULL,0,0 FROM players WHERE player_id='peter_youel';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,21,9,-12.33333333,3,13 FROM players WHERE player_id='quinn_brown';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.27272727,28,11,NULL,0,0 FROM players WHERE player_id='ralph_gonzalez';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.25000000,15,4,-9.00000000,1,6 FROM players WHERE player_id='reid_washkoviak';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.16666667,19,6,NULL,0,0 FROM players WHERE player_id='riley_walsh';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.50000000,6,2,NULL,0,0 FROM players WHERE player_id='ryan_carmody';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,2.66666667,16,3,NULL,0,0 FROM players WHERE player_id='ryan_hechmer';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.09523810,68,21,NULL,0,0 FROM players WHERE player_id='ryan_mccain';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.40000000,43,10,NULL,0,0 FROM players WHERE player_id='ryan_murray';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.88888889,31,9,NULL,0,0 FROM players WHERE player_id='scott_au_yeung';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.32000000,75,25,0.33333333,12,57 FROM players WHERE player_id='sebas_pires';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-1.20000000,13,5,NULL,0,0 FROM players WHERE player_id='sebastian_borjas';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.16666667,20,6,NULL,0,0 FROM players WHERE player_id='shiv_pandya';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.17647059,46,17,NULL,0,0 FROM players WHERE player_id='smith_mcgruder';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.05555556,61,18,3.66666667,9,36 FROM players WHERE player_id='spencer_lorenz';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.70588235,131,34,4.40000000,30,204 FROM players WHERE player_id='tad_bates';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.33333333,27,9,-5.25000000,4,13 FROM players WHERE player_id='teddy_allison';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.88888889,94,27,-16.00000000,1,17 FROM players WHERE player_id='teddy_skendzel';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.93103448,112,29,-2.16000000,25,95 FROM players WHERE player_id='thomas_rotatori';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.68421053,122,38,-6.12500000,8,27 FROM players WHERE player_id='tim_gannon';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.76000000,91,25,NULL,0,0 FROM players WHERE player_id='tj_carmody';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.34615385,96,26,-2.87500000,8,35 FROM players WHERE player_id='tommy_deiser';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.78260870,149,46,2.33333333,3,10 FROM players WHERE player_id='tommy_gasper';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,5,2,2.00000000,1,3 FROM players WHERE player_id='tripp_bergan';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.69230769,35,13,-1.00000000,3,4 FROM players WHERE player_id='vasco_esquivel';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,3.43636364,219,55,4.39393939,33,226 FROM players WHERE player_id='weston_lorenz';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.44444444,111,45,3.20000000,15,71 FROM players WHERE player_id='wil_antonius';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.16129032,101,31,-5.62500000,8,40 FROM players WHERE player_id='will_carter';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,-0.25000000,20,8,-1.00000000,1,1 FROM players WHERE player_id='will_dejulius';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.03076923,226,65,-4.00000000,15,63 FROM players WHERE player_id='will_esposito';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,10,3,NULL,0,0 FROM players WHERE player_id='will_jones';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,1.86538462,171,52,-0.56666667,30,141 FROM players WHERE player_id='will_stevens';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.40909091,77,22,0.00000000,4,18 FROM players WHERE player_id='will_weldon';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,4.87755102,208,49,0.76666667,30,182 FROM players WHERE player_id='xavier_hirsch';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.00000000,4,2,NULL,0,0 FROM players WHERE player_id='xavier_williams';
INSERT OR REPLACE INTO fantasy_player_baselines(player_id,batting_fp_per_game,career_pa,career_batting_gp,pitching_fp_per_app,career_pitching_apps,career_pitching_outs) SELECT player_id,0.25000000,12,4,NULL,0,0 FROM players WHERE player_id='zach_petko';
